server:
  port: 8102
  servlet:
    context-path: /uaa

spring:
  application:
    name: auth-server

eureka:
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://ad:ad@test.eureka.com:8761/eureka/
