server:
  port: 8104

spring:
  application:
    name: boot-demo
  boot:
    admin:
      client:
        url: "http://localhost:8100"
        instance:
          metadata:
            user.name: user
            user.password: 123456
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always